### ISSUE TITLE
Cancel Encoding Process?

### ISSUE THREAD

**Issue by jrgalim** [cyrildiagne/Shine-MP3-Encoder-on-AS3-Alchemy#2]
Greetings!  I love this mp3 encoder, but there doesn't appear to be any way to cancel the encoding process once it has been started.  Is this the case?

Thanks in advance,
-Jamie

**Comment by cyrildiagne** [comment]
Hey!
Wow that's indeed a good question. It surely can be done but its not
implemented yet on the C side nor the flash side.
Unfortunately I don't have time to work on this lib anymore, but it
would be a good improvement :)

Kikko

Sent from my iPhone

On 30 juil. 2011, at 18:38, jrgalim
reply@reply.github.com
wrote:

**Comment by jrgalim** [comment]
Ok cool, thanks for the reply!

-Jamie
